---
- hosts: printers
  become: yes
  gather_facts: true

  vars:
    destination: /home/mks/moonraker

  tasks:

  - name: Fix Moonraker data paths
    command: 
      cmd: sudo -u mks scripts/data-path-fix.sh
      chdir: "{{ destination }}"
