---
- hosts: printers
  become: true
  gather_facts: true

  tasks:
    
  - name: Restart moonraker.service
    ansible.builtin.systemd:
      name: moonraker.service
      state: restarted
    become: yes
