---
- hosts: printers
  become: true
  become_user: mks
  gather_facts: true

  vars:
    destination: /home/mks/klipper_config/printer.cfg

  tasks:
    - name: Remove default cruft from printer.config
      community.general.ini_file:
        path: "{{ destination }}"
        section: "{{ item }}" 
        state: absent
      loop:
        - adxl345
        - resonance_tester

    - name: Update max_accel_to_decel instructions
      ansible.builtin.replace:
        path: "{{ destination }}"
        regexp: "{{ item.old }}"
        replace: "{{ item.new | string }}"
      loop:
        - old: "^(.*)set RUN_DECEL(.*)$"
          new: !unsafe "    {% set RUN_CRUISE   = printer.configfile.settings['printer'].minimum_cruise_ratio|float %}"
        - old: "^(.*)ACCEL_TO_DECEL={RUN_DECEL}(.*)$"
          new: '    SET_VELOCITY_LIMIT VELOCITY={RUN_VELOCITY} ACCEL={RUN_ACCEL} MINIMUM_CRUISE_RATIO={RUN_CRUISE}'
        - old: "^max_accel_to_decel:(.*)$"
          new: '# max_accel_to_decel:\1 >> depricated'

- import_playbook: restart-klipper.yaml
